apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: rajeshvalluri11/mysql:v1
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 #Service Port
    targetPort: 80 #Container Port